; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_qtpy_esp32s2]
platform = espressif32
board = adafruit_qtpy_esp32s2
framework = arduino
board_microros_distro = jazzy
board_microros_transport = serial
monitor_speed = 115200
lib_deps = 
    https://github.com/micro-ROS/micro_ros_platformio
    sparkfun/SparkFun BNO080 Cortex Based IMU@^1.1.12

[bno085_common]
platform = espressif32
board = adafruit_qtpy_esp32s2
framework = arduino
board_microros_distro = jazzy
board_microros_transport = serial
monitor_speed = 115200
lib_deps = 
    https://github.com/micro-ROS/micro_ros_platformio
    sparkfun/SparkFun BNO080 Cortex Based IMU@^1.1.12

[env:bno085_quat]
extends = bno085_common
build_src_filter = 
	-<*>
    +<../bno085/bno085_quat.cpp>

[env:bno085_accel_gyro]
extends = bno085_common
build_src_filter = 
	-<*>
    +<../bno085/bno085_accel_gyro.cpp>

[env:lsm6dsox]
platform = espressif32
board = adafruit_qtpy_esp32s2
framework = arduino
board_microros_distro = jazzy
board_microros_transport = serial
monitor_speed = 115200
build_src_filter = 
	-<*>
    +<../lsm6dsox/lsm6dsox.cpp>
lib_deps = 
    https://github.com/micro-ROS/micro_ros_platformio
    adafruit/Adafruit LSM6DS@^4.7.4

[env:icm20649]
platform = espressif32
board = adafruit_qtpy_esp32s2
framework = arduino
board_microros_distro = jazzy
board_microros_transport = serial
monitor_speed = 115200
build_src_filter = 
	-<*>
    +<../icm20649/icm20649.cpp>
lib_deps = 
    https://github.com/micro-ROS/micro_ros_platformio
    adafruit/Adafruit ICM20X@^2.0.7